### ISSUE TITLE
Support of Symfony3

### ISSUE THREAD

**Issue by llaumgui** [romaricdrigon/MetaYaml#12]
Currently MetaYaml use Symfony2 dependancies. It's possible to upgrade to Sf3 ?

**Comment by romaricdrigon** [comment]
Loading from file was handling the "proper" way, so it should work with Symfony 3. Only thing is to run the tests to double-check.

**Comment by romaricdrigon** [comment]
I just tested, it works. By the end of the end I will release a new 1.1 version.

**Comment by romaricdrigon** [comment]
Ta-daa, version 1.1 is released :)

**Comment by llaumgui** [comment]
Thanks !
